plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidMultiplatformLibrary) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinJvm) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.ktor) apply false
}

// ===================================================================================================
// KAN-109 — i18n sync. The UX-authored, validated strings under ../Cryptasa/i18n are the single
// source of truth (SoT); Cyppie's per-module composeResources are GENERATED from it (never hand-edited).
//   ./gradlew syncI18n   one-way SoT → composeResources for every module/locale (the bootstrap is replaced)
//   ./gradlew checkI18n  CI drift gate: composeResources must equal the SoT projection; also verifies
//                        per-locale key parity, that every SoT key maps to a module, and no `\'` escapes
//                        (compose-resources wants a bare apostrophe, not a backslash-escaped one).
// SoT is one flat strings.xml per locale (all namespaces); each module owns a set of key prefixes.
// ===================================================================================================
run {
    val sotDir = file("../Cryptasa/i18n")
    // (label, module composeResources dir, owned key prefixes). pf_/send_/wc_ wire in when
    // :feature:portfolio (KAN-107) / Send (KAN-110) / WalletConnect (KAN-62) reach develop.
    val targets = listOf(
        Triple(
            "feature:onboarding",
            file("feature/onboarding/src/commonMain/composeResources"),
            listOf("onb_", "unlock_", "common_", "cd_"),
        ),
        Triple(
            "feature:wallet",
            file("feature/wallet/src/commonMain/composeResources"),
            // send_ + wc_ live here too: the Send UI (KAN-110) and the WalletConnect UI (KAN-126)
            // are both part of :feature:wallet (reuse the Send-Confirm disclosure).
            listOf("wallet_", "receive_", "home_", "token_", "nft_", "send_", "wc_", "common_"),
        ),
        Triple(
            "feature:portfolio",
            file("feature/portfolio/src/commonMain/composeResources"),
            listOf("pf_"),
        ),
        Triple(
            "feature:market",
            file("feature/market/src/commonMain/composeResources"),
            listOf("mkt_"),
        ),
    )
    // Prefixes owned by modules not yet on develop — keys here are intentionally not synced (no module),
    // but must still be "covered" so the unmapped-key check below doesn't flag them as lost.
    val pendingPrefixes = emptyList<String>()

    tasks.register("syncI18n") {
        group = "i18n"
        description = "Copy ../Cryptasa/i18n SoT → per-module composeResources (one-way; KAN-109)."
        val sot = sotDir
        val moduleTargets = targets
        doLast {
            require(sot.isDirectory) { "i18n SoT not found: $sot" }
            val stringRegex = Regex("<(string|plurals)\\s+name=\"([^\"]+)\"[^>]*>.*?</\\1>", RegexOption.DOT_MATCHES_ALL)
            val localeDirs = sot.listFiles { f -> f.isDirectory && f.name.startsWith("values") }!!.sortedBy { it.name }
            var written = 0
            moduleTargets.forEach { (label, moduleDir, prefixes) ->
                localeDirs.forEach { localeDir ->
                    val src = File(localeDir, "strings.xml")
                    if (!src.isFile) return@forEach
                    val xml = src.readText()
                    val picked = stringRegex.findAll(xml)
                        .filter { m -> prefixes.any { m.groupValues[2].startsWith(it) } }
                        .map { it.value }
                        .toList()
                    val out = buildString {
                        append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
                        append("<!-- GENERATED by ./gradlew syncI18n from ../Cryptasa/i18n (KAN-109). DO NOT EDIT. -->\n")
                        append("<resources>\n")
                        picked.forEach { append("  ").append(it).append("\n") }
                        append("</resources>\n")
                    }
                    val dest = File(File(moduleDir, localeDir.name), "strings.xml")
                    dest.parentFile.mkdirs()
                    dest.writeText(out)
                    written++
                }
                logger.lifecycle("syncI18n: $label ← ${localeDirs.size} locales")
            }
            logger.lifecycle("syncI18n: wrote $written files from SoT $sot")
        }
    }

    tasks.register("checkI18n") {
        group = "verification"
        description = "Fail if composeResources drift from the ../Cryptasa/i18n SoT (KAN-109 CI gate)."
        val sot = sotDir
        val moduleTargets = targets
        val pending = pendingPrefixes
        doLast {
            // Skip gracefully when the SoT sibling isn't checked out (keeps `check` green in CI contexts
            // without ../Cryptasa); the gate only enforces drift where the SoT is actually present.
            if (!sot.isDirectory) {
                logger.warn("checkI18n: SoT not present ($sot) — skipping i18n drift gate.")
                return@doLast
            }
            val stringRegex = Regex("<(string|plurals)\\s+name=\"([^\"]+)\"[^>]*>.*?</\\1>", RegexOption.DOT_MATCHES_ALL)
            fun keyOf(s: String) = Regex("name=\"([^\"]+)\"").find(s)!!.groupValues[1]
            val problems = mutableListOf<String>()

            val localeDirs = sot.listFiles { f -> f.isDirectory && f.name.startsWith("values") }!!.sortedBy { it.name }
            val baseDir = localeDirs.firstOrNull { it.name == "values" }
                ?: error("SoT has no base 'values' locale")
            val baseKeys = stringRegex.findAll(File(baseDir, "strings.xml").readText()).map { keyOf(it.value) }.toSet()

            // 1) per-locale key parity vs base
            localeDirs.forEach { localeDir ->
                val keys = stringRegex.findAll(File(localeDir, "strings.xml").readText()).map { keyOf(it.value) }.toSet()
                val missing = baseKeys - keys
                val extra = keys - baseKeys
                if (missing.isNotEmpty()) problems += "[parity] ${localeDir.name}: missing ${missing.size} keys (e.g. ${missing.take(5)})"
                if (extra.isNotEmpty()) problems += "[parity] ${localeDir.name}: ${extra.size} extra keys (e.g. ${extra.take(5)})"
            }

            // 2) no backslash-escaped apostrophe (compose-resources wants a bare ') — in the SoT *and*
            //    the generated composeResources (a stray hand-edit would slip past the SoT scan).
            localeDirs.forEach { localeDir ->
                val f = File(localeDir, "strings.xml")
                if (f.readText().contains("\\'")) problems += "[quote] SoT ${localeDir.name}/strings.xml contains a backslash-escaped apostrophe (\\') — use a bare '"
            }
            moduleTargets.forEach { (label, moduleDir, _) ->
                moduleDir.listFiles { d -> d.isDirectory && d.name.startsWith("values") }?.forEach { d ->
                    val f = File(d, "strings.xml")
                    if (f.isFile && f.readText().contains("\\'")) problems += "[quote] $label ${d.name}/strings.xml contains a backslash-escaped apostrophe (\\')"
                }
            }

            // 3) every base key must map to some module (present or pending) — else a key would be lost
            val allPrefixes = moduleTargets.flatMap { it.third } + pending
            val unmapped = baseKeys.filter { k -> allPrefixes.none { k.startsWith(it) } }.sorted()
            if (unmapped.isNotEmpty()) problems += "[mapping] ${unmapped.size} SoT keys map to no module: $unmapped"

            // 4) drift: each module's on-disk composeResources must equal the SoT projection
            moduleTargets.forEach { (label, moduleDir, prefixes) ->
                localeDirs.forEach { localeDir ->
                    val src = File(localeDir, "strings.xml")
                    val expected = buildString {
                        append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
                        append("<!-- GENERATED by ./gradlew syncI18n from ../Cryptasa/i18n (KAN-109). DO NOT EDIT. -->\n")
                        append("<resources>\n")
                        stringRegex.findAll(src.readText())
                            .filter { m -> prefixes.any { m.groupValues[2].startsWith(it) } }
                            .forEach { append("  ").append(it.value).append("\n") }
                        append("</resources>\n")
                    }
                    val dest = File(File(moduleDir, localeDir.name), "strings.xml")
                    if (!dest.isFile) problems += "[drift] $label ${localeDir.name}: missing (run ./gradlew syncI18n)"
                    else if (dest.readText() != expected) problems += "[drift] $label ${localeDir.name}/strings.xml differs from SoT (run ./gradlew syncI18n)"
                }
            }

            if (problems.isNotEmpty()) {
                throw GradleException("checkI18n found ${problems.size} issue(s):\n" + problems.joinToString("\n") { "  - $it" })
            }
            logger.lifecycle("checkI18n: OK — composeResources match SoT for ${moduleTargets.size} modules × ${localeDirs.size} locales.")
        }
    }

    // CI drift gate: any module's `check` runs checkI18n (skips itself if the SoT isn't present).
    allprojects {
        tasks.matching { it.name == "check" }.configureEach { dependsOn(rootProject.tasks.named("checkI18n")) }
    }
}

// KAN-131 — write the gitignored iOS xcconfig with the WalletConnect projectId from `wcProjectId`
// (single source = ~/.gradle/gradle.properties). Run before an Xcode/fastlane build; the value is never
// committed (Config.local.xcconfig is gitignored). Empty `wcProjectId` writes an empty value (app still runs).
tasks.register("generateWcIosConfig") {
    description = "Writes app/iosApp/Configuration/Config.local.xcconfig with WC_PROJECT_ID from `wcProjectId`."
    group = "ios"
    val projectId = (findProperty("wcProjectId") as String?).orEmpty()
    val outFile = layout.projectDirectory.file("app/iosApp/Configuration/Config.local.xcconfig").asFile
    outputs.file(outFile)
    doLast {
        outFile.writeText("WC_PROJECT_ID = $projectId\n")
        logger.lifecycle("generateWcIosConfig: wrote ${outFile.name} (WC_PROJECT_ID ${if (projectId.isEmpty()) "EMPTY" else "set"})")
    }
}